<?php

include_once 'os_reader.features.inc';

/**
 * Implements hook_menu().
 */
function os_reader_menu() {
  $items = array();

  $items['os-reader/copy-feed-to-news/%/%/%/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'os_reader_ajax_copy_feed_to_news',
    'page arguments' => array(2, 3, 4),
    'access callback' => 'os_reader_ajax_copy_feed_to_news_access',
    'access arguments' => array(2, 3, 5),
    'theme callback' => 'cp_theme_name',
  );

  $items['cp/build/features/os_rss_feed'] = array(
    'title' => 'OS RSS feed settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_reader_feed_settings'),
    'access callback' => 'spaces_access_admin',
  );

  $items['rss-feed'] = array(
    'title callback' => 'os_reader_feed_title_callback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_reader_importer_feed_create'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Title callback for a menu item.
 */
function os_reader_import_page_title($type) {
  return t('import @type', array('@type' => $type));
}

/**
 * Title callback;
 */
function os_reader_feed_title_callback() {
  return t('@site-name RSS Feeds', array('@site-name' => variable_get('site_name')));
}

/**
 * Implements hook_menu_alter().
 */
function os_reader_menu_alter(&$item) {
  $item['node/add/feed-importer']['access callback'] = 'os_reader_feed_importer_access_callback';
}

/**
 * Custom access callback - Verifying the user can add a feed importer although
 * the OS reader app is disabled.
 */
function os_reader_feed_importer_access_callback() {
  return _os_reader_feed_importer_access_callback("create");
}

/**
 * Helper function for determine the access permission for a node.
 *
 * @param $op
 *  The applied operation on the node.
 *
 * @return bool
 *  TRUE/FALSE for the operation which the user try to apply.
 */
function _os_reader_feed_importer_access_callback($op) {
  $string = "{$op} feed_importer content";
  if ($vsite = vsite_get_vsite()) {
    return og_user_access('node', $vsite->id, $string);
  }
  else {
    return user_access($string);
  }
}

/**
 * Implements hook_theme().
 */
function os_reader_theme() {
  return array(
    'os_reader' => array(
      'variables' => array(
        'view' => '',
        'importers' => '',
        'add_new' => '',
      ),
      'template' => 'os-reader',
      'path' => drupal_get_path('module', 'os_reader') . '/template',
    ),
    'os_reader_importer_bundles' => array(
      'variables' => array(
        'items' => '',
      ),
      'template' => 'os-reader-importer_bundles',
      'path' => drupal_get_path('module', 'os_reader') . '/template',
    ),
  );
}

/**
 * Access callback for the os reader news import.
 */
function os_reader_import_news_access_callback() {
  if ($vsite = vsite_get_vsite()) {
    return og_user_access('node', $vsite->id, 'create news content') || og_user_access('node', $vsite->id, 'create blog content');
  }

  return user_access('create news content') || user_access('create blog content');
}

/**
 * Page Callback; Display feed items which can be imported into vsite.
 */
function os_reader_import_news() {
  drupal_add_css(drupal_get_path('module', 'os_reader') . '/os_reader.css');
  drupal_add_js(drupal_get_path('module', 'os_reader') . '/os_reader.js');

  $item = menu_get_item();
  $feed_importer_nid = isset($item['map'][4]) ? $item['map'][4] : NULL;

  // Check if user is allowed to import feeds.
  if ($vsite = vsite_get_vsite()) {
    if (og_user_access('node', $vsite->id, 'create feed_importer content')) {
      $options = array('attributes' => array('class' => array('add-new')));
      $type = $item['map'][2] == 'news' ? 'feed-importer' : 'blog-import';
      $add_new = l(t('+ Add new'), 'node/add/' . $type, $options);
    }
  }

  $variables = array(
    'importers' => os_reader_get_importers_list($feed_importer_nid, $item['map'][2]),
    'view' => views_embed_view('os_reader_feeds', 'default', $feed_importer_nid),
    'add_new' => empty($add_new) ? '' : $add_new,
  );

  return theme('os_reader', $variables);
}

/**
 * hook_views_query_alter().
 */
function os_reader_views_query_alter(&$view, views_plugin_query_default &$query) {
  if ($view->name != 'os_reader_feeds') {
    return;
  }

  $menu = menu_get_item();
  $type = $menu['original_map'][2];

  $group_key = key($query->where);
  $query->add_where($group_key, 'os_feed_item.importer_type', $type);
}

/**
 * Helper function for import news screen; Returns list of feed importer nodes.
 *
 * @param $feed_importer_nid
 *  Currently viewed importer, will get class 'active'.
 * @param $type
 *  The of the feed importer.
 *
 * @return string
 *  Themed item list of feed importers.
 */
function os_reader_get_importers_list($feed_importer_nid = NULL, $type) {
  // Get all feed importer nodes.
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type == 'blog' ? 'blog_import' : 'feed_importer')
    ->propertyCondition('status', NODE_PUBLISHED);

  // Display only feeds from this viste.
  if ($vsite = vsite_get_vsite()) {
    $query->fieldCondition(OG_AUDIENCE_FIELD, 'target_id', $vsite->id);
  }

  $result = $query->execute();

  if (empty($result['node'])) {
    // No feed importer nodes.
    return t('No feed importers found.');
  }
  $importers = node_load_multiple(array_keys($result['node']));

  // Create item list of feed importers.
  $items = array(
    array(
      'data' => l(t('All feeds'), 'cp/os-importer/' . $type . '/manage'),
      'class' => empty($feed_importer_nid) ? array('active') : array(),
    ),
  );
  foreach ($importers as $importer) {
    if ($feed_importer_nid == $importer->nid) {
      // Currently viewed importer, display as active text.
      $items[] = array(
        'data' => check_plain($importer->title),
        'class' => array('active'),
      );
    }
    else {
      // Display importer as link.
      $items[] = array(
        'data' => l($importer->title, 'cp/os-importer/' . $type . '/manage/' . $importer->nid),
      );
    }
  }

  return theme('item_list', array('items' => $items));
}

/**
 * Access callback; Feed item copy.
 *
 * @param $feed_id
 *  The feed ID.
 * @param $nid
 *  The vsite node ID.
 * @param $token
 *  Security token.
 *
 * @return bool
 *  Return true/false whether the user has access to copy the feed.
 */
function os_reader_ajax_copy_feed_to_news_access($feed_id, $nid, $token) {
  if (!drupal_valid_token($token, $feed_id . ':' . $nid)) {
    // Not a valid token.
    return;
  }

  $feed = os_reader_feed_item_load($feed_id);
  if (!og_user_access('node', $nid, 'create ' . $feed->type . ' content')) {
    // User does not have access to create "News" in VSite.
    return;
  }

  if (!os_reader_feed_item_load($feed_id)) {
    // Not a valid feed item.
    return;
  }

  return TRUE;
}

/**
 * AJAX callback for bind feed item to node.
 *
 * @param $feed_id
 *  The feed ID.
 * @param $vsite_id
 *  The vsite ID.
 * @param string $ajax
 */
function os_reader_ajax_copy_feed_to_news($feed_id, $vsite_nid, $ajax = 'nojs') {
  $feed = os_reader_feed_item_load($feed_id);
  $vsite = vsite_get_vsite($vsite_nid);
  $vsite_id = $vsite->id;
  $current_vsite = vsite_get_vsite();

  $importer = os_reader_copy_feed_item_to_news($feed, $vsite);

  if ($ajax == 'ajax') {
    $generic_message = t('Imported to @vsite. ', array('@vsite' => $vsite->og->title)) . l(t('Edit'), 'node/' . $importer->nid);
    $vsite_message = t('Imported. !edit', array('!edit' => l(t('Edit'), 'node/' . $importer->nid)));
    $message = empty($current_vsite) ?  $generic_message : $vsite_message;

    $commands[] = ajax_command_html("#feed-{$feed_id}-{$vsite_id}", $message);
    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
  }
  else {
    drupal_set_message(t('Feed item added to @vsite', array('@vsite' => $vsite->og->title)));
    drupal_goto('cp/os-importer/' . $feed->importer_type . '/manage');
  }
}

/**
 * Implements hook_os_app_info().
 */
function os_reader_os_app_info() {
  $apps = array();

  $apps['os_reader'] = array(
    'path' => 'reader',
  	'nodetypes' => array(
  	  'feed',
      'feed_importer',
    ),
    'views tabs' => array(
      'reader' => array('page'),
    ),
    'searchable' => FALSE,
    'importers' => array(
      'feed' => array(
        'csv' => 'os_feed',
      ),
    ),
  );

  return $apps;
}

/**
 * Implements hook_vsite_og_node_type_info().
 */
function os_reader_vsite_og_node_type_info() {
  return array(
    'feed' => 'group content',
    'blog_import' => 'group content',
    'feed_importer' => 'group content',
  );
}

/**
 * Implements hook_entity_info().
 */
function os_reader_entity_info() {
  return array(
    'os_feed_item' => array(
      'label' => t('OS feed item'),
      'entity class' => 'Entity',
      'base table' => 'os_feed_item',
      'fieldable' => TRUE,
      'controller class' => 'EntityAPIController',
      'entity keys' => array(
        'id' => 'id',
        'label' => 'title',
        'bundle' => 'type',
      ),
      'bundles' => array(
        'feed_item' => array(
          'label' => '',
          'admin' => array(
            'path' => 'admin/config/content/os_feed/manage/os_feed',
            'real path' => 'admin/config/content/os_feed/manage/os_feed',
            'access arguments' => array('os_feed manage'),
          ),
        ),
      ),
      'views controller class' => 'OsReaderViewsController',
      'metadata controller class' => 'OsReaderMetadataController',
    ),
  );
}

/**
 * Create an OS feed item object.
 *
 * @param $values
 *  The initialized values of the OS feed item object.
 *
 * @return Entity
 *  The entity object of the OS feed item entry.
 */
function os_reader_feed_item_create($values = array()) {
  $values += array(
    'type' => 'feed_item',
    'created' => time(),
  );

  return entity_create('os_feed_item', $values);
}

/**
 * Load an OS feed item entry.
 *
 * @param $id
 *  The OS feed item identifier.
 *
 * @return Entity
 *  The OS feed item object.
 */
function os_reader_feed_item_load($id) {
  return entity_load_single('os_feed_item', $id);
}

/**
 * Load multiple OS feed item entries.
 *
 * @param $ids
 *  List of IDs to load.
 *
 * @return Entity
 *  List of OS feed item entries.
 */
function os_reader_feed_item_load_multiple($ids) {
  return entity_load('os_feed_item', $ids);
}

/**
 * Delete multiple imported entities.
 *
 * @param $ids
 *  The identifiers of the imported entities.
 */
function os_reader_feed_item_delete_multiple($ids) {
  entity_delete_multiple('os_feed_item', $ids);
}

/**
 * Implements hook_feeds_plugins().
 */
function os_reader_feeds_plugins() {
  $info = array();
  $info['OsFeedReaderFetcher'] = array(
    'name' => t('OS feed reader fetcher'),
    'description' => t('Fetch info from a out source.'),
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'OsFeedReaderFetcher',
      'file' => 'OsFeedReaderFetcher.inc',
      'path' => drupal_get_path('module', 'os_reader') . '/plugins',
    ),
  );
  $info['OsFeedFetcher'] = array(
    'name'        => t('OS feed fetcher'),
    'description' => t('Fetch feed item from urls.'),
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class'  => 'OsFeedFetcher',
      'file'   => 'OsFeedFetcher.inc',
      'path'   => drupal_get_path('module', 'os_reader') . '/plugins',
    ),
  );
  return $info;
}

/**
 * Create a news node based on a feed item.
 *
 * @param $feed
 *  The feed object to copy.
 * @param $vsite
 *  VSITE object to which to assign the new node.
 *
 * @return
 *  The newly created node object.
 */
function os_reader_copy_feed_item_to_news($feed, $vsite) {
  global $user;

  // Check if the feed was already imported to the VSite.
  $news_node = os_reader_get_news_by_feed_item($feed->id, $vsite->id);
  if (!empty($news_node)) {
    // Feed already imported to VSite.
    return $news_node;
  }

  // Create the "News" node.
  $node = new stdClass();
  $node->type = $feed->importer_type;
  $node->title = $feed->title;
  $node->language = LANGUAGE_NONE;

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->body->set(array('value' => $feed->description, 'format' => 'filtered_html'));
  $wrapper->{OG_AUDIENCE_FIELD}->set(array($vsite->id));
  $wrapper->author->set($user->uid);

  if ($feed->importer_type == 'news') {
    // Get the first image src.
    $file = FALSE;
    $doc = new DOMDocument();

    // todo: use os_copy_file();
    try {
      if ($feed->description) {
        $doc->loadHTML($feed->description);
        $images = $doc->getElementsByTagName('img')->item(0);

        if ($images && method_exists($images, 'getAttribute') && $src = $images->getAttribute('src')) {
          $file = system_retrieve_file($src, 'public://', TRUE);
        }
      }
    }
    catch (Exception $e) {
      watchdog('os_reader', t('There was a problem when importing the feed item: @message', array('@message' => filter_xss($e->getMessage()))));
    }

    $wrapper->field_news_date->set($feed->created);
    $wrapper->field_url->set(array('url' => $feed->url));
    if ($file) {
      $wrapper->field_photo->set((array) $file);
    }
  }
  $wrapper->save();

  // Reference the feed to the VSite.
  $feed_wrapper = entity_metadata_wrapper('os_feed_item', $feed);
  $feed_wrapper->field_vsites_reference[] = $vsite->id;

  // Reference the feed to the News node.
  $feed_wrapper->field_nodes_reference[] = $node->nid;
  $feed_wrapper->save();

  return $node;
}

/**
 * Get news node that was imported from a given OS feed item in a given VSite.
 *
 * @param $feed_id
 *  The feed ID.
 * @param $vsite_id
 *  The VSite ID.
 *
 * @return bool
 *  Return node object of the news node related to the feed item if the feed
 */
function os_reader_get_news_by_feed_item($feed_id, $vsite_id) {
  // Load news nodes that were imported from the given feed item.
  $wrapper_feed = entity_metadata_wrapper('os_feed_item', $feed_id);
  $news_nodes = $wrapper_feed->field_nodes_reference->value();

  if (empty($news_nodes)) {
    // No imported news nodes.
    return FALSE;
  }

  // Run through imported news nodes to see if any of them belong to the VSite.
  foreach ($news_nodes as $news_node) {
    $wrapper_news = entity_metadata_wrapper('node', $news_node);

    if (!empty($wrapper_news->og_group_ref) && $wrapper_news->og_group_ref->get(0)->getIdentifier() == $vsite_id) {
      // Found news node that matches both feed item and VSite.
      return $news_node;
    }
  }

  // Feed item was not imported to VSite.
  return FALSE;
}

/**
 * Node preprocess.
 */
function os_reader_process_node(&$variables) {
  if ($variables['type'] == 'news') {
    if ($variables['view_mode'] == 'teaser' && !$variables['page']) {
      // On the news page allow the next HTML tags in the body field.
      $variables['content']['body'][0]['#markup'] = preg_replace("/<img[^>]+\>/i", " ", $variables['content']['body'][0]['#markup']);
    }

    if (os_reader_get_feed_item_by_nid($variables['node']->nid)) {
      // When watching an imported news item - don't apply the site time zone.
      $date = new DateTime(NULL, timezone_open('UTC'));
      $date->setTimestamp($variables['content']['field_news_date']['#items'][0]['value']);
      $vars['content']['field_news_date'][0]['#markup'] = $date->format('F j, Y');
    }
  }

  // When accessing an importer node redirect the user to the importing page.
  if ($variables['page'] && in_array($variables['type'], array('feed_importer', 'blog_import'))) {
    $type = $variables['type'] == 'blog_import' ? 'blog' : 'news';
    $url = 'cp/os-importer/' . $type . '/manage';

    if ($vsite = vsite_get_vsite()) {
      $node = node_load($variables['nid']);
      $purl = $vsite->group->purl;

      if (!isset($vsite->group->purl) && is_array($node->purl) && !empty($node->purl['value'])) {
        $purl = $node->purl['value'];
      }

      $url = $purl . '/' . $url;
    }

    drupal_goto($type, array('fragment' => 'overlay=' . $url));
  }
}

/**
 * Implementing hook_form_alter().
 */
function os_reader_form_alter(&$form, $form_state, $form_id) {
  if (!in_array($form_id, array('feed_importer_node_form', 'blog_import_node_form'))) {
    return;
  }

  // Remove field 'Feeds'.
  $form['feeds']['#access'] = FALSE;

  // Place URL field before title field.
  $form['field_rss_url']['#weight'] = -6;

  // Add description to title field.
  $form['title']['#description'] = t('Administrative title used to describe this feed ex. \'Sports from The Gazette\'.');

  hide($form['menu']);
}

/**
 * Implements hook_form_FORM_ID_alter(); Remove filter when not inside a VSite.
 */
function os_reader_form_views_exposed_form_alter(&$form, &$form_state) {
  if (empty($form['feed_is_imported'])) {
    // Not os-reader exposed form.
    return;
  }

  // Change option '-Any-' to 'All'.
  $form['feed_is_imported']['#options']['All'] = t('All');

  $vsite = vsite_get_vsite();

  if (empty($vsite)) {
    // Not in a VSite, remove views filter.
    $form['#info'] = array();
    $form['submit']['#access'] = FALSE;
    $form['feed_is_imported']['#access'] = FALSE;
    $form['feed_by_text']['#access'] = FALSE;
  }
}

/**
 * Check if a news item is relate to feed item.
 *
 * @param $nid
 *  The news NID.
 *
 * @return bool
 *  return TRUE/FALSE if the news item is an imported feed item.
 */
function os_reader_get_feed_item_by_nid($nid) {
  $query = new entityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'os_feed_item')
    ->fieldCondition('field_nodes_reference', 'target_id', $nid)
    ->execute();

  return !empty($result['os_feed_item']);
}

/**
 * Implements hook_cron().
 */
function os_reader_cron() {
  $id = variable_get('os_reader_last_feed_item', 0);

  // Get all the orphans feed items which older then 1 month.
  $query = db_select('os_feed_item', 'ofi');
  $query->leftJoin('og_membership', 'ogm', 'ogm.etid = ofi.id');
  $results = $query
    ->fields('ofi', array('id'))
    ->condition('ofi.id', 0, '>')
    ->condition('ofi.created', strtotime("1 month ago"), '<')
    ->condition('ofi.id', $id, '>=')
    ->isNull('ogm.etid')
    ->range(0, 500)
    ->orderBy('ofi.created', 'DESC')
    ->execute()
    ->fetchAllAssoc('id');

  if (empty($results)) {
    return;
  }

  // Delete the feed items and save the last one we processed.
  os_reader_feed_item_delete_multiple(array_keys($results));
  variable_set('os_reader_last_feed_item', end($results)->id);
}

/**
 * Generate links for predefined terms and bundles.
 *
 * @param $content_types
 *  Lists of selected content types.
 * @param $vocabs
 *  Lists of selected vocabularies.
 *
 * @return Array
 *  Array of links.
 */
function os_reader_importer_feed_links($content_types, $vocabs) {
  $links = $items = array();

  if (!empty($content_types)) {
    $items = array();

    foreach ($content_types as $bundle) {
      if ($bundle) {
        $items[] = array('key' => $bundle, 'link' => node_type_get_name($bundle));
      }
    }

    $links['bundles'] = _os_reader_importer_feed_create($items, 'type');
  }

  if (!empty($vocabs)) {
    $items = array();
    foreach ($vocabs as $terms) {
      $taxonomy_terms = taxonomy_term_load_multiple($terms);

      foreach ($taxonomy_terms as $term) {
        $items[] = array('key' => $term->tid, 'link' => $term->name);
      }
    }

    $links['terms'] = _os_reader_importer_feed_create($items, 'term');
  }

  return $links;
}

/**
 * Supply form for create RSS feed links.
 */
function os_reader_importer_feed_create($form, $form_state) {
  if (!module_exists('vsite')) {
    return;
  }

  if (!empty($form_state['input'])) {
    // The user submitted the form but the JS is disabled.
    $links = os_reader_importer_feed_links($form_state['input']['os_rss_feed_content_types'], $form_state['input']['os_rss_feed_vocabs']);

    $links = array_merge($links['bundles'], $links['terms']);

    $form['results'] = array(
      '#type' => 'item',
      '#markup' => implode("<br />", $links),
    );

    $form['go_back'] = array(
      '#type' => 'item',
      '#markup' => t('<a href="@url">Go back</a> and select more filters.', array('@url' => url('rss-feed'))),
    );

    return $form;
  }

  $selected_bundles = variable_get('os_rss_feed_content_types', array());
  $selected_vocabularies = variable_get('os_rss_feed_vocabs', array());

  $form = os_reader_importer_feed_element();

  $links = os_reader_importer_feed_links($selected_bundles, $selected_vocabularies);

  $form['pre_defined'] = array(
    '#type' => 'item',
    '#markup' => theme('os_reader_importer_bundles', array(
      'title' => t('You can use predefined feeds:'),
      'items' => $links['bundles'],
    )),
    '#weight' => -10,
  );

  // Display only the bundle the manager selected.
  foreach ($selected_bundles as $key => $bundle) {
    if (!$bundle) {
      unset($form['os_rss_feed_content_types']['#options'][$key]);
    }
  }

  // Display only selected vocabularies.
  foreach ($selected_vocabularies as $key => $vocab) {
    if (!$vocab) {
      unset($form['os_rss_feed_vocabs'][$key]);
    }
  }

  $form['#attached']['js'][] = drupal_get_path('module', 'os_reader') . '/js/os_rss_feed_submission.js';

  $form['actions'] = array(
    '#type' => 'actions',
    '#weight' => 10,
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    ),
  );

  $form['results'] = array(
    '#type' => 'item',
    '#weight' => 11,
    '#markup' => '',
    '#prefix' => '<div id="os_rss_feed_results">',
    '#suffix' => '</div>',
  );

  $form['#attached']['css'][] = drupal_get_path('module', 'os_reader') . '/css/os_rss_feed_results.css';

  return $form;
}

/**
 * Return commons form elements: vocabularies and bundles for selection.
 *
 * @param $values
 *  Default value of the form. Allowed values:
 *    - content_types: The content types.
 *    - selected_terms: The selected terms IDs.
 *
 * @return Array
 *  Form elements.
 */
function os_reader_importer_feed_element($values = array()) {
  global $base_url;

  $form = array();

  $values += array(
    'content_types' => array(),
    'selected_terms' => array(),
  );

  if (empty($values['content_types'])) {
    $values['content_types'] = array(
      'news',
      'blog',
      'events',
      'presentation',
      'biblio',
    );
  }

  $form['os_rss_feed_content_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Content types'),
    '#options' => os_get_bundles(array(1)),
    '#description' => t('Select the content types whose rss deeds will be shown by default.'),
    '#default_value' => $values['content_types'],
  );

  $vsite = vsite_get_vsite();
  ctools_include('taxonomy', 'vsite_vocab');
  $vocabs = vsite_vocab_get_vocabularies($vsite);

  // The 'vocabs' tree will contain select fields - one for each vocabulary.
  $vocab_form = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#title' => t('Filter by Vocabulary'),
    '#description' => t('Only include posts tagged with terms from the following vocabularies.'),
    '#tree' => TRUE,
    '#attached' => array(
      'css' => array(libraries_get_path('select2') . '/select2.css'),
      'js' => array(
        array('type' => 'setting', 'data' => array(
          'sv_list_vocab_bundles' => $vocabs,
          'url' => $base_url,
        )),
        libraries_get_path('select2') . '/select2.js',
        drupal_get_path('module', 'os_reader') . '/js/os_rss_feed_vocabs.js',
      ),
    ),
  );

  // Create a select field for each vocabulary, with the vocabulary's terms as
  // the field's options.
  foreach (array_keys($vocabs) as $vid) {
    $vocabulary = taxonomy_vocabulary_load($vid);

    // Get the vocabulary's terms.
    $terms = array();
    foreach (taxonomy_get_tree($vid) as $item) {
      $term = taxonomy_term_load($item->tid);
      $terms[$term->tid] = $term->name;
    }

    $element = 'vocab_' . $vid;
    $vocab_default_value = (isset($values['selected_terms'][$element])) ? $values['selected_terms'][$element] : array();

    // Create select field with the terms as options.
    $vocab_form[$element] = array(
      '#type' => 'select',
      '#options' => $terms,
      '#title' => $vocabulary->name,
      '#multiple' => TRUE,
      '#default_value' => $vocab_default_value,
      '#description' => t('Select vocab/terms that will show on RSS links in the page.'),
      '#attributes' => array('class' => array('terms-select')),
    );
  }

  $form['os_rss_feed_vocabs'] = $vocab_form;

  return $form;
}

/**
 * Build the links for the RSS.
 *
 * @param $items
 *  Arrays of items that will be rendered to links. The validate structure is:
 *    - key: The value which the node will be filtered by
 *    - link: The title of the feed.
 * @param $key
 *  The name of the query argument which hold the value that will be filter by.
 *
 * @return Array
 *  Array of rendered links.
 *
 * @code
 *  $taxonomy_terms = taxonomy_term_load_multiple($terms);
 *  foreach ($taxonomy_terms as $term) {
 *    $items[] = array('key' => $term->tid, 'link' => $term->name);
 *  }
 *
 * $links = array_merge($links, _os_reader_importer_feed_create($items, 'term'));
 * @endcode
 *
 * @see os_reader_importer_feed_create().
 */
function _os_reader_importer_feed_create($items, $key) {
  $links = array();
  foreach ($items as $item) {
    $options = array(
      'query' => array(
        $key => $item['key'],
      ),
    );

    $links[] = l($item['link'], 'os_rss_feed_export', $options);
  }

  return $links;
}

/**
 * Get the node IDs according the the filter criteria.
 */
function os_reader_importer_feed_export() {
  if (!empty($_GET['type']) && !empty($_GET['term'])) {
    $data = array(
      'bundle' => explode(',', $_GET['type']),
      'term' => explode(',', $_GET['term']),
    );
  }
  else if (!empty($_GET['type'])) {
    $data['bundle'] = explode(',', $_GET['type']);
  }
  elseif (!empty($_GET['term'])) {
    $data['term'] = explode(',', $_GET['term']);
  }
  else {
    return;
  }

  $nids = os_reader_importer_feed_get_nids($data);
  return implode(",", $nids);
}

/**
 * Build the Content with the RSS feeds.
 *
 * @param $info
 *  Array of search criteria with of one of the next filters:
 *    - bundle: Array of bundles.
 *    - term: Array of term IDs.
 *
 * @return Array
 *  List of node IDs.
 */
function os_reader_importer_feed_get_nids($info) {
  $nids = array();

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node');

  if (module_exists('vsite') && $vsite = vsite_get_vsite()) {
    $query->fieldCondition(OG_AUDIENCE_FIELD, 'target_id', $vsite->id);
  }

  if (!empty($info['bundle'])) {
    $query->propertyCondition('type', $info['bundle'], 'IN');
  }

  if (!empty($info['term'])) {
    $query->fieldCondition(OG_VOCAB_FIELD, 'target_id', $info['term']);
  }

  $results = $query->execute();

  if (!empty($results['node'])) {
    $nids = array_keys($results['node']);
  }

  return $nids;
}

/**
 * Implements hook_context_load_alter().
 */
function os_reader_context_load_alter(&$context) {
  if ($context->name != 'os_rss_feed') {
    return;
  }

  // The context of the rss feed is not node context. Adding the export_module
  // key and the settings_link key will add for the context a settings button.
  $context->export_module = 'os_rss_feed';
  $context->settings_link = TRUE;
}

/**
 * Create a predefined RSS feeds.
 */
function os_reader_feed_settings($form, $form_settings) {
  $values = array(
    'content_types' => variable_get('os_rss_feed_content_types', array()),
    'selected_terms' => variable_get('os_rss_feed_vocabs', array()),
  );
  $form = os_reader_importer_feed_element($values);

  return system_settings_form($form);
}
