<?php
/**
 * @file
 * os_reader.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function os_reader_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'os_feed_item-feed_item-field_nodes_reference'
  $field_instances['os_feed_item-feed_item-field_nodes_reference'] = array(
    'bundle' => 'feed_item',
    'default_value' => NULL,
    'default_value_function' => '',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'os_feed_item',
    'field_name' => 'field_nodes_reference',
    'label' => 'News reference',
    'required' => 0,
    'settings' => array(
      'behaviors' => array(
        'prepopulate' => array(
          'status' => 0,
        ),
      ),
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'show_identifier' => 1,
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'os_feed_item-feed_item-field_vsites_reference'
  $field_instances['os_feed_item-feed_item-field_vsites_reference'] = array(
    'bundle' => 'feed_item',
    'default_value' => NULL,
    'default_value_function' => '',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'os_feed_item',
    'field_name' => 'field_vsites_reference',
    'label' => 'VSites reference',
    'required' => 0,
    'settings' => array(
      'behaviors' => array(
        'prepopulate' => array(
          'status' => 0,
        ),
      ),
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'show_identifier' => 1,
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('News reference');
  t('VSites reference');

  return $field_instances;
}
